version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20 # Use Node.js 20 runtime
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Zipping Lambda package..."
      - zip -r lambda-package.zip ./ -x buildspec.yml
      - echo "Build completed."
  post_build:
    commands:
      # Deploy Lambda Function Code
      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name lambda_s3_manual_deployment_function --zip-file fileb://lambda-package.zip
      - echo "Lambda function code updated."
      - sleep 10
      - aws lambda update-function-configuration --function-name lambda_s3_manual_deployment_function --handler lambda.handler

      # Interact with S3 Bucket
      - echo "Interacting with S3 bucket..."
      - aws s3 cp lambda-package.zip s3://s3-bucket-cloud-formation/
      - aws s3 ls s3://s3-bucket-cloud-formation/

      # Interact with EC2 Instance
      - echo "Describing EC2 instance..."
      - aws ec2 describe-instances --filters "Name=tag:Name,Values=ec2_app_server_cloud_formation" --query "Reservations[].Instances[].InstanceId" --output text

      # Interact with RDS
      - echo "Describing RDS instance..."
      - aws rds describe-db-instances --db-instance-identifier rds-instance --query "DBInstances[].Endpoint.Address" --output text

      - echo "Post-build steps completed."

artifacts:
  files:
    - lambda-package.zip
